oauth2-server-url: http://localhost:9401
security:
  oauth2:
    client:
      access-token-uri: ${oauth2-server-url}/oauth/token
      client-id: client-app-2
      client-secret: 666
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
server:
  port: 8081
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID01